# Generated by Django 4.2.1 on 2023-05-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='box',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='box',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
