# Generated by Django 4.2.1 on 2023-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0002_remove_box_created_by_remove_box_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='box',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
